### Update Post 
PATCH http://localhost:3000/posts
Content-Type: application/json

{
    "id": 6, 
    "title": "ReactJS is Lame",
    "postType": "POST",
    "slug": "react-js2",
    "status": "DRAFT",
    "content": "tets Content",
    "tags": [1,3]

}