POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoibmljb0BuaWNvLmlvIiwiaWF0IjoxNzc5Mjc5OTk0LCJleHAiOjE3NzkyODM1OTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.QmUh5FD_U2hlc8CirxkHAvTlm04rZY8yzhgbnxdGZ00

{
    "title": "Vue",
    "postType": "POST",
    "slug": "vue-js",
    "status": "DRAFT",
    "content": "Simple API with NodeJS",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\":\"Person\"\r\n}",
    "featuredImageUrl": "www.sample.com",
    "publishOn": "2026-05-18T11:36:50.512Z",
    "metaOptions": {
        "metaValue" : "{\"sidebarEnable\" : true,\"footerActive\" : true}"
    },
    "tags": [1, 9]
}
