POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Angular is opinioneted framework",
    "postType": "POST",
    "slug": "angular-js-framework",
    "status": "DRAFT",
    "content": "tets Content",
    "schema": "{\r\n \"@context\": \"https:\/\/schema.org\",\r\n \"@type\":\"Person\"\r\n}",
    "featuredImageUrl": "www.sample.com",
    "publishOn": "2024-03-16T07:46:32+0000",
    "tags": ["NestJS", "TypeScript"],
    "metaOptions": {
        "metaValue" : "{\"sidebarEnable\" : true,\"footerActive\" : true}"
    },
    "authorId": 1
}
