### Creating New Users
POST http://localhost:3000/users
Content-Type: application/json


{
  "firstName": "Heri",
  "lastName": "Pratama",
  "email": "heri@herihoo.io",
  "password": "heriheri1234*"
}