### Creating New Users
POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImVtYWlsIjoibmljb0BuaWNvLmlvIiwiaWF0IjoxNzc5MjcwMzcwLCJleHAiOjE3NzkyNzM5NzAsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.R65EDUEDklQ5ZBKFXKfRarTK6ujjF9q3cwe1-s_ZiCI

{
    "users": [
        {
          "firstName": "Burhanudin",
          "lastName": "Rabbani",
          "email": "ganteng@bani.io",
          "password": "banibani1234*"
        },
        {
          "firstName": "Risaldi",
          "lastName": "Sedeki",
          "email": "risl@icang.io",
          "password": "banibani1234*"
        }
    ]
}
