### Create New Tags
POST http://localhost:3000/tags
Content-Type: application/json

{
    "name": "NestJs",
    "slug": "nest-js",
    "description": "This tag is used for posts related to nest-js topics."
}