### Create New Tags
POST http://localhost:3000/tags
Content-Type: application/json

{
    "name": "Modern JavaScript",
    "slug": "modern-javascript",
    "description": "This tag is used for posts related to JavaScript topics."
}